$(document).ready(function() {
     $('#normally_bg').click(function normally_bg() {
         $("body").css("background-color", "");
         $("body").css("color", "");
         $("a").css("color", "");
         $("h1").css("color", "");
         $("h2").css("color", "");
         $("h2").css("color", "");
         $("h3").css("color", "");
         $("h4").css("color", "");
         $("h5").css("color", "");
         $("h6").css("color", "");
         $("p").css("color", "");
         $("li").css("color","");
         $("li i,li div").css("color", "");
         $("small").css("color", "");
         $("marquee").css("color", "");
         // $("img").css("filter", "grayscale(100%)");
         $(".f-1").css("color", "");
         $(".f-1").css("background-color", "");
         $(".f-2").css("color", "");
         $(".f-2").css("background-color", "");
         $(".f-3").css("color", "F00");
         $(".f-3").css("background-color", "");
         $(".btn-main").css("background-color", "");
         $(".btn-main").css("color", "");
         $(".white-bg").css("background-color", "");
         $(".bg-main").css("background-color", "");
         $(".title-header").css("border-bottom", "");
         $(".title-news").css("color","");
         $(".news-info").css("background-color","");
         $(".news-info").css("border-bottom", "");
         $(".card-body").css("background-color","");
         $(".title-card").css("color","");
         $(".title-bg").css("background-color","");
         $(".breadcrumb-menu").css("color","");
         $(".breadcrumb-menu .active").css("color","");
         $(".form-label").css("color","");
         $(".form-control-search-header").css("color","");
         $(".media-bg").css("background-color", "");
         $(".dropdown-menu").css("background-color", "");
         $(".rounded-border").css("border", "");
         $(".page-item .page-link").css("color", "");
         $(".page-item .page-link").css("background-color", "");
         $(".page-item.active .page-link").css("color", "");
         $(".page-item.active .page-link").css("background-color", "");
         $(".contact-footer").css("color", "");
         $("footer").css("background-color", "");
         $("footer").css("border-top", "");
         $(".comfooter").css("background-color", "");
         $(".comfooter").css("color", "");
     });
 });
 
 $(document).ready(function() {
     $('#black_bg').click(function black_bg() {
         $("body").css("background-color", "#000");
         $("body").css("color", "#FFF");
         $("a").css("color", "#FFF");
         $("h1").css("color", "#FFF");
         $("h2").css("color", "#FFF");
         $("h2").css("color", "#FFF");
         $("h3").css("color", "#FFF");
         $("h4").css("color", "#FFF");
         $("h5").css("color", "#FFF");
         $("h6").css("color", "#FFF");
         $("p").css("color", "#FFF");
         $("li").css("color","#FFF");
         $("li i,li div").css("color", "#FFF");
         $("small").css("color", "#FFF");
         $("marquee").css("color", "#FFF");
         // $("img").css("filter", "grayscale(100%)");
         $(".f-1").css("color", "#FFF");
         $(".f-1").css("background-color", "none");
         $(".f-2").css("color", "#FFF");
         $(".f-2").css("background-color", "#000");
         $(".f-3").css("color", "#FFFF00");
         $(".f-3").css("background-color", "#000");
         $(".btn-main").css("background-color", "#FFF");
         $(".btn-main").css("color", "#000");
         $(".white-bg").css("background-color", "#000");
         $(".bg-main").css("background-color", "#000");
         $(".title-header").css("border-bottom", "3px #FFF solid");
         $(".title-news").css("color","#FFF");
         $(".news-info").css("background-color","#000");
         $(".news-info").css("border-bottom", "1px #FFF solid");
         $(".card-body").css("background-color","#000");
         $(".title-card").css("color","#000");
         $(".title-bg").css("background-color","#FFF");
         $(".breadcrumb-menu").css("color","#000");
         $(".breadcrumb-menu .active").css("color","#000");
         $(".form-label").css("color","#FFF");
         $(".form-control-search-header").css("color","#FFF");
         $(".form-control-search-header").css("backgroubd-color","none");
         $(".form-control-search-header").css("border-color","#FFF");
         $(".media-bg").css("background-color", "#000");
         $(".dropdown-menu").css("background-color", "#000");
         $(".rounded-border").css("border", "1px #FFF solid");
         $(".page-item .page-link").css("color", "#FFF");
         $(".page-item .page-link").css("background-color", "#707070");
         $(".page-item.active .page-link").css("color", "#000");
         $(".page-item.active .page-link").css("background-color", "#FFF");
         $(".contact-footer").css("color", "#FFF");
         $("footer").css("background-color", "#000");
         $("footer").css("border-top", "1px #FFF solid");
         $(".comfooter").css("background-color", "#FFF");
         $(".comfooter").css("color", "#000");
     });
 });
 
 $(document).ready(function() {
     $('#yellow_bg').click(function yellow_bg() {
         $("body").css("background-color", "#000");
         $("body").css("color", "#FFFF00");
         $("a").css("color", "#FFFF00");
         $("h1").css("color", "#FFFF00");
         $("h2").css("color", "#FFFF00");
         $("h2").css("color", "#FFFF00");
         $("h3").css("color", "#FFFF00");
         $("h4").css("color", "#FFFF00");
         $("h5").css("color", "#FFFF00");
         $("h6").css("color", "#FFFF00");
         $("p").css("color", "#FFFF00");
         $("li").css("color","#FFFF00");
         $("li i,li div").css("color", "#FFFF00");
         $("small").css("color", "#FFFF00");
         $("marquee").css("color", "#FFFF00");
         // $("img").css("filter", "sepia(100%)");
         $(".f-1").css("color", "#FFF");
         $(".f-1").css("background-color", "none");
         $(".f-2").css("color", "#FFF");
         $(".f-2").css("background-color", "#000");
         $(".f-3").css("color", "#FFFF00");
         $(".f-3").css("background-color", "#000");
         $(".btn-main").css("background-color", "#FFFF00");
         $(".btn-main").css("color", "#000");
         $(".white-bg").css("background-color", "#000");
         $(".bg-main").css("background-color", "#000");
         $(".title-header").css("border-bottom", "3px #FFFF00 solid");
         $(".title-news").css("color","#FFFF00");
         $(".news-info").css("background-color","#000");
         $(".news-info").css("border-bottom", "1px #FFFF00 solid");
         $(".card-body").css("background-color","#000");
         $(".title-card").css("color","#000");
         $(".title-bg").css("background-color","#FFFF00");
         $(".breadcrumb-menu").css("color","#000");
         $(".breadcrumb-menu .active").css("color","#000");
         $(".form-label").css("color","#FFFF00");
         $(".media-bg").css("background-color", "#000");
         $(".dropdown-menu").css("background-color", "#000");
         $(".rounded-border").css("border", "1px #FFFF00 solid");
         $(".page-item .page-link").css("color", "#FFFF00");
         $(".page-item .page-link").css("background-color", "#707070");
         $(".page-item.active .page-link").css("color", "#000");
         $(".page-item.active .page-link").css("background-color", "#FFFF00");
         $(".contact-footer").css("color", "#FFFF00");
         $("footer").css("background-color", "#000");
         $("footer").css("border-top", "1px #FFFF00 solid");
         $(".comfooter").css("background-color", "#FFFF00");
         $(".comfooter").css("color", "#000");
     });
 });